spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/delivery
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    secret: secret
  h2:
    console:
      enabled: true
